### ISSUE TITLE
O Crash using Deviation PI

### ISSUE THREAD

**Issue by rgleason** [RooieDirk/Deviation_pi#3]
Is this deviation message in logbook?
1:01:10 AM: Getting DefaultSystemLocale...
11:01:10 AM: Found LanguageInfo for: English
11:01:11 AM:    ***GPS Watchdog timeout at Lat:33.358   Lon: -79.282
11:02:09 AM: LOGBOOK:  2018-03-22 15:02:09 UTC  DR Lat   33.35800 Lon  -79.28200

**Comment by rgleason** [comment]
Another crash saving the deviation table.

11:17:56 AM: Loading catalog for opencpn core.
11:17:56 AM: Getting DefaultSystemLocale...
11:17:56 AM: Found LanguageInfo for: English
11:17:56 AM:    ***GPS Watchdog timeout at Lat:33.358   Lon: -79.282
11:18:55 AM: LOGBOOK:  2018-03-22 15:18:55 UTC  DR Lat   33.35800 Lon  -79.28200

**Comment by rgleason** [comment]
Another one not sure what caused it.

11:34:35 AM: Loading catalog for:  opencpn-weather_routing_pi
11:34:35 AM: Loading catalog for:  opencpn-wmm_pi
11:34:35 AM: Loading catalog for opencpn core.
11:34:35 AM: Getting DefaultSystemLocale...
11:34:35 AM: Found LanguageInfo for: English
11:34:36 AM:    ***GPS Watchdog timeout at Lat:33.358   Lon: -79.282

**Comment by RooieDirk** [comment]
Rick,
At the moment no log messages are written by the PI.
I'll try to update some code this week
